spring.datasource.url=jdbc:mysql://localhost:3306/stocksentry
spring.datasource.username=YOUR_DB_USERNAME
spring.datasource.password=YOUR_DB_PASSWORD

jwt.secret=YOUR_JWT_SECRET

finnhub.api.key=YOUR_FINNHUB_API_KEY
newsapi.api.key=YOUR_NEWSAPI_API_KEY

twilio.account.sid=YOUR_TWILIO_ACCOUNT_SID
twilio.auth.token=YOUR_TWILIO_AUTH_TOKEN
twilio.whatsapp.number=YOUR_TWILIO_WHATSAPP_NUMBER

sendgrid.api.key=YOUR_SENDGRID_API_KEY